title: morugon
description: 「いいよ」のおすそ分け、くらしのキュレーション
theme: minima
url: "https://ka428387.github.io"
baseurl: "/morugon"
lang: ja_JP
show_excerpts: true
author_name: kasumi
twitter_url: "https://twitter.com/ka_428"
instagram_url: "https://www.instagram.com/cuboro_s/"
header_pages: []
minima:
  date_format: "%Y年%-m月%-d日"
