title: morugon
description: 「いいよ」のおすそ分け、くらしのキュレーション
theme: minima

url: "https://ka428387.github.io"
baseurl: "/morugon"

# 1ページに表示する設定など（必要になったら触ればOK）
show_excerpts: true

# ── プロフィール用 ──
author_name: kasumi
twitter_url: "https://twitter.com/ka_428"
instagram_url: "https://www.instagram.com/cuboro_s/"

# ヘッダーに自動表示するページを制御（空にして自動追加を防ぐ）
header_pages: []
